# Generated by Django 2.2.1 on 2019-05-18 05:11

from django.db import migrations, models
import django.utils.timezone
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20190518_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='meta_description',
            field=models.CharField(default=django.utils.timezone.now, help_text='Brief description that shows up in Google search. Approx. 160 characters.', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=filebrowser.fields.FileBrowseField(blank=True, help_text='Image featured in post. Must be at least 1,000x1,000', max_length=500, verbose_name='Featured image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='header_title',
            field=models.CharField(help_text='Title that shows on page.', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='meta_title',
            field=models.CharField(help_text='Title that shows up in Google search.', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='modification_date',
            field=models.DateTimeField(blank=True, help_text='Date the post was modified from original version.'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_slug',
            field=models.SlugField(blank=True, help_text='Text that shows in URL.', unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='publication_date',
            field=models.DateTimeField(blank=True, help_text='Original publication date.'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail_image',
            field=filebrowser.fields.FileBrowseField(blank=True, help_text='Thumbnail image used across site. Must be at least 1,000x1,000', max_length=500, verbose_name='Thumbnail image'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
