# Generated by Django 2.2.1 on 2019-05-19 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20190518_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='modification_date',
            field=models.DateTimeField(help_text='Date the post was modified from original version.'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publication_date',
            field=models.DateTimeField(help_text='Original publication date.'),
        ),
    ]
