# Generated by Django 2.2.1 on 2019-05-19 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20190519_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header_title',
            field=models.CharField(help_text='Title that shows on page. Should typically match meta title.', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Brief description that shows up in Google search. Approx. 160 characters.', max_length=250),
        ),
        migrations.AlterField(
            model_name='post',
            name='modification_date',
            field=models.DateTimeField(auto_now=True, help_text='Date the post was modified from original version.'),
        ),
    ]
