# Generated by Django 2.2.1 on 2019-05-19 02:14

from django.db import migrations, models
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20190519_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_slug',
            field=models.SlugField(blank=True, help_text='Text that shows in URL. Will automatically populate when object is saved.', unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Check the box to publish category.'),
        ),
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=filebrowser.fields.FileBrowseField(blank=True, help_text='Image featured in post. Must be at least 1,000px X 1,000px', max_length=500, verbose_name='Featured image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_slug',
            field=models.SlugField(blank=True, help_text='Text that shows in URL. Will automatically populate when object is saved.', unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail_image',
            field=filebrowser.fields.FileBrowseField(blank=True, help_text='Thumbnail image used across site. Must be at least 1,000px X 1,000px', max_length=500, verbose_name='Thumbnail image'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_name',
            field=models.CharField(help_text='Tag should be short. 1 or 2 words and less than 50 characters.', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_slug',
            field=models.SlugField(blank=True, help_text='Text that shows in URL. Will automatically populate when object is saved.', unique=True),
        ),
    ]
