# Generated by Django 2.2.1 on 2019-05-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20190519_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header_title',
            field=models.CharField(blank=True, help_text='Title that shows on page. Should typically match meta title.', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Brief description that shows up in Google search. Approx. 160 characters.', max_length=250),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_category',
            field=models.ManyToManyField(blank=True, to='posts.Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_tag',
            field=models.ManyToManyField(blank=True, to='posts.Tag'),
        ),
    ]
