# Generated by Django 2.2.1 on 2019-05-19 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20190519_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Brief description that shows up in Google search. Approx. 160 characters.', max_length=250),
        ),
    ]
