# Generated by Django 2.2.1 on 2019-05-25 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20190519_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='custom_css',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='custom_js',
            field=models.TextField(blank=True),
        ),
    ]
