# Generated by Django 2.2.1 on 2019-05-30 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20190525_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_slug',
            field=models.SlugField(blank=True, help_text='Text that shows in URL. Will automatically populate when object is saved.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_slug',
            field=models.SlugField(blank=True, help_text='Text that shows in URL. Will automatically populate when object is saved.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_slug',
            field=models.SlugField(blank=True, help_text='Text that shows in URL. Will automatically populate when object is saved.', max_length=255, unique=True),
        ),
    ]
