# Generated by Django 2.2.1 on 2019-05-30 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20190530_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header_title',
            field=models.CharField(blank=True, help_text='Title that shows on page. Should typically match meta title.', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='meta_title',
            field=models.CharField(help_text='Title that shows up in Google search.', max_length=200, unique=True),
        ),
    ]
