# Generated by Django 2.2.1 on 2019-06-07 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20190530_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_tag',
            field=models.ManyToManyField(blank=True, null=True, to='posts.Tag'),
        ),
    ]
