# Generated by Django 2.2.1 on 2019-05-17 19:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('event_start', models.DateField(default=datetime.date.today)),
                ('event_end', models.DateField(default=datetime.date.today)),
                ('event_address', models.CharField(max_length=500)),
            ],
        ),
    ]
