# Generated by Django 2.2.1 on 2019-05-17 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_partner_partner_description'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_partners',
            field=models.ManyToManyField(to='partners.Partner'),
        ),
    ]
