# Generated by Django 2.2.1 on 2019-05-19 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_event_partners'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Check the box to publish event.'),
        ),
    ]
