# Generated by Django 2.2.1 on 2019-05-19 20:14

from django.db import migrations
import localflavor.generic.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_country',
            field=localflavor.generic.models.IBANField(blank=True, include_countries=None, max_length=34, use_nordea_extensions=False),
        ),
    ]
