# Generated by Django 2.2.1 on 2019-05-19 20:15

from django.db import migrations
import localflavor.generic.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_event_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_country',
            field=localflavor.generic.models.BICField(blank=True, max_length=11),
        ),
    ]
