# Generated by Django 2.2.1 on 2019-05-19 20:18

from django.db import migrations
import localflavor.generic.models
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20190519_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_country',
            field=localflavor.generic.models.IBANField(blank=True, include_countries=('AT', 'BE', 'BG', 'CH', 'CY', 'CZ', 'DE', 'DK', 'EE', 'ES', 'FI', 'FR', 'GB', 'GI', 'GR', 'HR', 'HU', 'IE', 'IS', 'IT', 'LI', 'LT', 'LU', 'LV', 'MC', 'MT', 'NL', 'NO', 'PL', 'PT', 'RO', 'SE', 'SI', 'SK', 'SM'), max_length=34, use_nordea_extensions=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_state',
            field=localflavor.us.models.USStateField(blank=True, max_length=2, null=True),
        ),
    ]
