# Generated by Django 2.2.1 on 2019-05-19 20:21

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20190519_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
