# Generated by Django 2.2.1 on 2019-05-19 20:32

from django.db import migrations
import django_countries.fields
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20190519_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_state',
            field=localflavor.us.models.USStateField(blank=True, max_length=2, null=True, verbose_name='Event state (US only)'),
        ),
    ]
