# Generated by Django 2.2.1 on 2019-06-02 19:43

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20190519_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_country',
            field=django_countries.fields.CountryField(blank=True, default='US', max_length=2, null=True),
        ),
    ]
