# Generated by Django 2.2.1 on 2019-06-07 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20190602_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_zipcode',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
