# Generated by Django 2.2.1 on 2019-06-07 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_event_event_zipcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_zipcode',
        ),
        migrations.AddField(
            model_name='event',
            name='event_zip_code',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
