# Generated by Django 2.2.1 on 2019-06-07 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_auto_20190607_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_zip_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
