# Generated by Django 2.2.1 on 2019-06-07 20:33

from django.db import migrations
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_auto_20190607_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_image',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=1000, null=True, verbose_name='Event image'),
        ),
    ]
