# Generated by Django 2.2.1 on 2019-06-25 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_event_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_venue',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
