# Generated by Django 2.2.1 on 2019-08-15 02:40

from django.db import migrations
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_auto_20190815_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=1000, null=True, verbose_name='Event image'),
        ),
    ]
