# Generated by Django 2.2.1 on 2019-05-17 23:01

from django.db import migrations
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='partner_logo',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=1000, verbose_name='Image'),
        ),
    ]
