# Generated by Django 2.2.1 on 2019-05-17 23:54

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_partner_partner_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='partner_description',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Content'),
        ),
    ]
