# Generated by Django 2.2.1 on 2019-05-19 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0006_auto_20190518_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Check the box to publish Partner.'),
        ),
    ]
