# Generated by Django 2.2.1 on 2019-06-07 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0007_partner_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='partner_listing_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
