# Generated by Django 2.2.1 on 2019-05-23 22:03

from django.db import migrations, models
import filebrowser.fields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=False, help_text='Check the box to publish page.')),
                ('meta_title', models.CharField(help_text='Title that shows up in Google search.', max_length=100, unique=True)),
                ('header_title', models.CharField(blank=True, help_text='Title that shows on page. Should typically match meta title.', max_length=100, unique=True)),
                ('meta_description', models.CharField(blank=True, help_text='Brief description that shows up in Google search. Approx. 160 characters.', max_length=250)),
                ('featured_image', filebrowser.fields.FileBrowseField(blank=True, help_text='Image featured on page. Must be at least 1,000px X 1,000px', max_length=500, verbose_name='Featured image')),
                ('show_cta', models.BooleanField(default=False, help_text='Check the box to show CTA.')),
                ('page_content', tinymce.models.HTMLField(blank=True, verbose_name='Content')),
                ('page_slug', models.SlugField(blank=True, help_text='Text that shows in URL. Will automatically populate when object is saved.', unique=True)),
                ('custom_js', models.TextField(blank=True)),
                ('custom_css', models.TextField(blank=True)),
            ],
        ),
    ]
