# Generated by Django 2.2.1 on 2019-05-30 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_slug',
            field=models.SlugField(blank=True, help_text='Text that shows in URL. Will automatically populate when object is saved.', max_length=255, unique=True),
        ),
    ]
